title: A Byte at a Time
author:
  name: 'Michelle Ho'
  email: 'michelle.y.ho@gmail.com'


description:
  Personal blog tracking adventure in software engineering

theme: minima
minima:
  skin: solarized-dark

